# NUMPY Array Operations

In [3]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("Basic Step: ", arr[1:9:2])
print("Negative indexing: ", arr[-5:-1])

Basic Slicing:  [3 4 5 6 7]
Basic Step:  [2 4 6 8]
Negative indexing:  [6 7 8 9]


In [8]:
arr_2d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print("Specific Element: ", arr_2d[0,2])
print("Specific Row: ", arr_2d[1])
print("Specific Column: ", arr_2d[:,0])

Specific Element:  3
Specific Row:  [4 5 6]
Specific Column:  [1 4 7]


## Sorting

In [7]:
unsorted = np.array([2,4,1,8,3,53,2,])
print("sorted array: ", np.sort(unsorted))

arr_2d_unsorted= np.array([[3,1],
                           [1,2],
                           [2,3]])

print("Sorted 2D Array by column-wise: ", np.sort(arr_2d_unsorted,axis=0))      # columwise 2d array sorting
print("Sorted 2D Array by row-wise: ", np.sort(arr_2d_unsorted,axis=1))         # rowwise 2d array sorting

sorted array:  [ 1  2  2  3  4  8 53]
Sorted 2D Array by column-wise:  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array by row-wise:  [[1 3]
 [1 2]
 [2 3]]


## Filter

In [4]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("even numbers: ", even_number)

even numbers:  [ 2  4  6  8 10]


## Filter with Mask

In [ ]:
mask = arr_2d_unsorted < 3
print("numbers less than 5: ", arr_2d_unsorted[mask])

numbers less than 5:  [1 1]


## Fancy indexing vs np.where()

In [ ]:
indexing = [0,2,4]
print(numbers[indexing])

where_number = np.where(numbers >5 )
print(numbers[where_number])

[1 3 5]
[ 6  7  8  9 10]


In [18]:
condition_array = np.where(numbers>5,numbers*2,numbers*5)
print(condition_array)

[ 5 10 15 20 25 12 14 16 18 20]


## Adding and Removing data

In [ ]:
arr1=[1,2,3]
arr2=[4,5,6]

print("full array: ", np.concatenate((arr1,arr2)))

full array:  [1 2 3 4 5 6]


## Array Compatibility

In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9,10])

print("compatibility shapes: ", a.shape == b.shape)
print("compatibility shapes: ", a.shape == c.shape)

compatibility shapes:  True
compatibility shapes:  False


## Add New Columns and Rows

In [ ]:
original=np.array([[1,2],
                   [3,4]])
new_row=np.array([[5,6]])
new_col=np.array([[7],[8]])

print("Original Row: ", original)

add_new_row=np.vstack((original,new_row))
print(add_new_row)

add_new_column=np.hstack((original,new_col))
print(add_new_column)

Original Row:  [[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


## Delete Operation

In [34]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
mask_array=[2,3,4,5,6,7]
deleted=np.delete(ar,mask_array)
print(deleted)

[ 1  2  9 10]
