# Numpy array and basics
### learn about numpy

In [2]:
import numpy as np

### Numpy version

In [4]:
np.__version__

'2.2.5'

### Memory Size

In [5]:
vec=np.array([1,2,3,4,5])
print(vec.__sizeof__())

152


### creating array from list

In [6]:
arr_1d=np.array([1,2,3,4,5])
print("the 1d array :",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("the 2d array :",arr_2d)

the 1d array : [1 2 3 4 5]
the 2d array : [[1 2 3]
 [4 5 6]]


### python_list vs numpy_array

In [12]:
py_list=[1,2,3,4,5]
print("Python list multiplication", py_list*2)

np_array=np.array([1,2,3,4,5])
print("Numpy array multiplication", np_array*2)
import time as tm

start = tm.time()
pyn_list=[i*2 for i in range(1000000)]
print("\n list operational time :", tm.time()-start)


start=tm.time()
npy_array=np.arange(1000000)*2
print("\n numpy operational time :", tm.time()-start)


Python list multiplication [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication [ 2  4  6  8 10]

 list operational time : 0.18491291999816895

 numpy operational time : 0.014394283294677734


### creating array from scratch

In [ ]:
arr_zeros=np.zeros((4,3))
print("zeros array: \n", arr_zeros)     # zeros array

arr_ones=np.ones((3,4))
print("ones array: \n", arr_ones)       # ones array

arr_const_value=np.full((2,2),7)
print("constant array values: \n", arr_const_value)   # conatant number array

random_num=np.random.random((2,3))*100
print("random numbers array: ", random_num)           # random numbers array

sequence=np.arange(1,30,4)
print("sequence array: ", sequence)                   #sequence array

zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
constant array values: 
 [[7 7]
 [7 7]]
random numbers array:  [[99.36516657 48.10823647 55.62389221]
 [13.92794463 78.72151067 40.06765779]]
sequence array:  [ 0  4  8 12 16]


### Vector , Matrices and Tensor

In [11]:
vector = np.array([1,2,3,4,5])
print("vector: ", vector)

matrices= np.array([[1,2,3],
                    [3,4,5],
                    [5,6,7]])
print("matrices: \n", matrices)

tensor =  np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("tensor: \n", tensor)


vector:  [1 2 3 4 5]
matrices: 
 [[1 2 3]
 [3 4 5]
 [5 6 7]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###  Array Properties

In [12]:
arr= np.array([[1,2,3],
               [4,5,6]])
print("shape: ", arr.shape)       # how many rows and column
print("dimension: ", arr.ndim)        # dimension
print("size: ", arr.size)        # array size
print("Data_type: ", arr.dtype)       # array datatype

shape:  (2, 3)
dimension:  2
size:  6
Data_type:  int64


### Array Reshaping

In [18]:
arr = np.arange(12)
print("Original Array: ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array: \n", reshaped)

flattened = reshaped.flatten()
print("flattened Array: \n", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("raveled Array: \n", raveled)

#Transpose
transpose = reshaped.T
print("transposed Array: \n", transpose)


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
