# Revision 
## phase-1

In [1]:
import numpy as np
import time as tm

In [ ]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)
print("operational time: ",)
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
start=tm.time()
py_list=[i for i in range(1000000)]
print("python list compute time: ", tm.time()-start)

start=tm.time()
py_array=np.arange(1000000)
print("numpy array compute time: ", tm.time()-start)

python list compute time:  0.42364954948425293
numpy array compute time:  0.01415872573852539


In [3]:
ar_1d=np.array([1,2,3,4,5])
ar_2d=np.array([[1,2],
                   [3,4],
                   [5,6]])
tensor=np.array([[[1],[2]],
                 [[3],[4]]])
print(ar_1d)
print(ar_2d)
print(tensor)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
[[[1]
  [2]]

 [[3]
  [4]]]


In [5]:
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(3, 3)
2
9
int64


In [11]:
c=np.arange(15)
print(c)
d=c.reshape(5,3)
print(c.reshape(5,3))
print(d.flatten())
print(d.ravel())
print(d.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


# Revision
## phase-2

In [12]:
print(c[5:9])
print(c[7:12:2])
print(c[-11:-4])

[5 6 7 8]
[ 7  9 11]
[ 4  5  6  7  8  9 10]


In [15]:
print(d[(2,1)])
print(d[4])
print(d[:,2])

7
[12 13 14]
[ 2  5  8 11 14]


In [20]:
unsorted=np.array([2,5,8,3,2,4])
e=np.array([[2,6],
            [5,2],
            [7,3]])
print(np.sort(unsorted))
print(np.sort(e,axis=1))
print(np.sort(e,axis=0))

[2 2 3 4 5 8]
[[2 6]
 [2 5]
 [3 7]]
[[2 2]
 [5 3]
 [7 6]]


In [ ]:
numbers=np.arange(20)
print(numbers[numbers%2==0])

mask=numbers>4
print(numbers[mask])

[ 0  2  4  6  8 10 12 14 16 18]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
null_vec=np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
print(null_vec.__sizeof__())

192
